// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockFailingERC20$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockFailingERC20";
  readonly sourceName: "contracts/mocks/MockFailingERC20.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"address","name":"","type":"address"},{"internalType":"uint256","name":"","type":"uint256"}],"name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x608060405234801561000f575f80fd5b5060d58061001c5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c806323b872dd14602a575b5f80fd5b603d6035366004606b565b5f9392505050565b604051901515815260200160405180910390f35b80356001600160a01b03811681146066575f80fd5b919050565b5f805f60608486031215607c575f80fd5b6083846051565b9250608f602085016051565b915060408401359050925092509256fea264697066735822122091caf6a04b55666b84605bcc4485367b7d1dd8cffc44262bbc275e9adb5a28c164736f6c63430008180033";
  readonly deployedBytecode: "0x6080604052348015600e575f80fd5b50600436106026575f3560e01c806323b872dd14602a575b5f80fd5b603d6035366004606b565b5f9392505050565b604051901515815260200160405180910390f35b80356001600160a01b03811681146066575f80fd5b919050565b5f805f60608486031215607c575f80fd5b6083846051565b9250608f602085016051565b915060408401359050925092509256fea264697066735822122091caf6a04b55666b84605bcc4485367b7d1dd8cffc44262bbc275e9adb5a28c164736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/mocks/MockFailingERC20.sol";
  readonly buildInfoId: "solc-0_8_24-d3688a7d5f6b70e4805ecfc0a6d64b88dc71eb0b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockFailingERC20"]: MockFailingERC20$Type;
    ["contracts/mocks/MockFailingERC20.sol:MockFailingERC20"]: MockFailingERC20$Type;
  }
}